// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kingdom-view/KingdomIsometric.tsx": () => import("../components/mockups/kingdom-view/KingdomIsometric.tsx"),
  "./components/mockups/world-map/WorldMapLoK.tsx": () => import("../components/mockups/world-map/WorldMapLoK.tsx")
};
